# Use the official PostgreSQL image as a parent image
FROM postgres:latest

# Set environment variables for PostgreSQL
ENV POSTGRES_DB=deliverydb
ENV POSTGRES_USER=usr
ENV POSTGRES_PASSWORD=pwd

# Expose the port PostgreSQL runs on
EXPOSE 5432